# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_operon_Rcpp <- function(all_scores, operon_two, matches_to_all_scores) {
    .Call(`_ECFGenomeRcpp_do_operon_Rcpp`, all_scores, operon_two, matches_to_all_scores)
}

rcpp_hello_world <- function() {
    .Call(`_ECFGenomeRcpp_rcpp_hello_world`)
}

rcpparma_hello_world <- function() {
    .Call(`_ECFGenomeRcpp_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_ECFGenomeRcpp_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_ECFGenomeRcpp_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_ECFGenomeRcpp_rcpparma_bothproducts`, x)
}

scoreseq_plus_single2 <- function(pwm35, sequences) {
    .Call(`_ECFGenomeRcpp_scoreseq_plus_single2`, pwm35, sequences)
}

scoreseq_plus_combinatoric2 <- function(pwm35, pwm10, sequences, spacer) {
    .Call(`_ECFGenomeRcpp_scoreseq_plus_combinatoric2`, pwm35, pwm10, sequences, spacer)
}

sum_which_greater <- function(of_int, to_sum, avector) {
    .Call(`_ECFGenomeRcpp_sum_which_greater`, of_int, to_sum, avector)
}

sum_which_greater_or_equal <- function(x, y, z) {
    .Call(`_ECFGenomeRcpp_sum_which_greater_or_equal`, x, y, z)
}

